# Generated by Django 5.1.2 on 2025-01-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('is_banned', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('about', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'female'), (0, 'male'), (2, 'not specified')], default=2)),
                ('height', models.PositiveIntegerField()),
                ('orientation', models.IntegerField(choices=[(2, 'bisexual'), (1, 'homosexual'), (0, 'heterosexual'), (3, 'asexual')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
