# Generated by Django 5.1.2 on 2024-12-15 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_banned", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("about", models.CharField(blank=True, max_length=256, null=True)),
                ("age", models.PositiveIntegerField(editable=False)),
                ("height", models.PositiveIntegerField()),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            (1, "homosexual"),
                            (0, "heterosexual"),
                            (3, "asexual"),
                            (2, "bisexual"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
