# Generated by Django 5.1.2 on 2024-12-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="orientation",
            field=models.IntegerField(
                choices=[
                    (0, "heterosexual"),
                    (3, "asexual"),
                    (2, "bisexual"),
                    (1, "homosexual"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                choices=[(2, "not specified"), (0, "male"), (1, "female")], default=2
            ),
        ),
    ]
