# Generated by Django 5.1.2 on 2024-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0002_profile_orientation_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "female"), (2, "not specified"), (0, "male")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="orientation",
            field=models.IntegerField(
                choices=[
                    (1, "homosexual"),
                    (2, "bisexual"),
                    (3, "asexual"),
                    (0, "heterosexual"),
                ],
                default=0,
            ),
        ),
    ]
