# Generated by Django 5.1.2 on 2024-12-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0003_alter_profile_age_alter_profile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(
                choices=[(1, "female"), (0, "male"), (2, "not specified")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="orientation",
            field=models.IntegerField(
                choices=[
                    (0, "heterosexual"),
                    (3, "asexual"),
                    (2, "bisexual"),
                    (1, "homosexual"),
                ],
                default=0,
            ),
        ),
    ]
