# Generated by Django 5.1.2 on 2025-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0006_alter_profile_gender_alter_profile_orientation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="orientation",
            field=models.IntegerField(
                choices=[
                    (3, "asexual"),
                    (0, "heterosexual"),
                    (2, "bisexual"),
                    (1, "homosexual"),
                ],
                default=0,
            ),
        ),
    ]
